server:
  port: 8085

spring:
  application:
    name: CONFIG_SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ambuj-dubey/Microservices
          default-label: master
          clone-on-start: true